-- SQL Export for table: dim_zone
-- Generated on: 2025-09-30 13:24:16.492493
-- Total records: 66

-- Create table structure
CREATE TABLE dim_zone (
    LocationID INT,
    Zone VARCHAR(35),
    Borough VARCHAR(13),
    centroid_lat VARCHAR(10),
    centroid_lon VARCHAR(10),
    polygon_id VARCHAR(10)
);

-- Insert data
INSERT INTO dim_zone (LocationID, Zone, Borough, centroid_lat, centroid_lon, polygon_id) VALUES
    (1, 'Newark Airport', 'EWR', NULL, NULL, NULL),
    (2, 'Jamaica Bay', 'Queens', NULL, NULL, NULL),
    (3, 'Allerton/Pelham Gardens', 'Bronx', NULL, NULL, NULL),
    (4, 'Alphabet City', 'Manhattan', NULL, NULL, NULL),
    (5, 'Arden Heights', 'Staten Island', NULL, NULL, NULL),
    (6, 'Arrochar/Fort Wadsworth', 'Staten Island', NULL, NULL, NULL),
    (7, 'Astoria', 'Queens', NULL, NULL, NULL),
    (8, 'Astoria Park', 'Queens', NULL, NULL, NULL),
    (9, 'Auburndale', 'Queens', NULL, NULL, NULL),
    (10, 'Baisley Park', 'Queens', NULL, NULL, NULL),
    (11, 'Bath Beach', 'Brooklyn', NULL, NULL, NULL),
    (12, 'Battery Park', 'Manhattan', NULL, NULL, NULL),
    (13, 'Battery Park City', 'Manhattan', NULL, NULL, NULL),
    (14, 'Bay Ridge', 'Brooklyn', NULL, NULL, NULL),
    (15, 'Bay Terrace/Fort Totten', 'Queens', NULL, NULL, NULL),
    (16, 'Bayside', 'Queens', NULL, NULL, NULL),
    (17, 'Bedford', 'Brooklyn', NULL, NULL, NULL),
    (18, 'Bedford Park', 'Bronx', NULL, NULL, NULL),
    (19, 'Bellerose', 'Queens', NULL, NULL, NULL),
    (20, 'Belmont', 'Bronx', NULL, NULL, NULL),
    (21, 'Bensonhurst East', 'Brooklyn', NULL, NULL, NULL),
    (22, 'Bensonhurst West', 'Brooklyn', NULL, NULL, NULL),
    (23, 'Bloomfield/Emerson Hill', 'Staten Island', NULL, NULL, NULL),
    (24, 'Bloomingdale', 'Manhattan', NULL, NULL, NULL),
    (25, 'Boerum Hill', 'Brooklyn', NULL, NULL, NULL),
    (26, 'Borough Park', 'Brooklyn', NULL, NULL, NULL),
    (27, 'Breezy Point/Fort Tilden/Riis Beach', 'Queens', NULL, NULL, NULL),
    (28, 'Brighton Beach', 'Brooklyn', NULL, NULL, NULL),
    (29, 'Broad Channel', 'Queens', NULL, NULL, NULL),
    (30, 'Bronx Park', 'Bronx', NULL, NULL, NULL),
    (31, 'Bronxdale', 'Bronx', NULL, NULL, NULL),
    (32, 'Brooklyn Heights', 'Brooklyn', NULL, NULL, NULL),
    (33, 'Brooklyn Navy Yard', 'Brooklyn', NULL, NULL, NULL),
    (34, 'Brownsville', 'Brooklyn', NULL, NULL, NULL),
    (35, 'Bushwick North', 'Brooklyn', NULL, NULL, NULL),
    (36, 'Bushwick South', 'Brooklyn', NULL, NULL, NULL),
    (37, 'Cambria Heights', 'Queens', NULL, NULL, NULL),
    (38, 'Canarsie', 'Brooklyn', NULL, NULL, NULL),
    (39, 'Carroll Gardens', 'Brooklyn', NULL, NULL, NULL),
    (40, 'Central Harlem', 'Manhattan', NULL, NULL, NULL),
    (41, 'Central Harlem North', 'Manhattan', NULL, NULL, NULL),
    (42, 'Central Park', 'Manhattan', NULL, NULL, NULL),
    (43, 'Charleston/Tottenville', 'Staten Island', NULL, NULL, NULL),
    (44, 'Chinatown', 'Manhattan', NULL, NULL, NULL),
    (45, 'City Island', 'Bronx', NULL, NULL, NULL),
    (46, 'Claremont/Bathgate', 'Bronx', NULL, NULL, NULL),
    (47, 'Clinton East', 'Manhattan', NULL, NULL, NULL),
    (48, 'Clinton Hill', 'Brooklyn', NULL, NULL, NULL),
    (49, 'Clinton West', 'Manhattan', NULL, NULL, NULL),
    (50, 'Co-Op City', 'Bronx', NULL, NULL, NULL),
    (132, 'JFK Airport', 'Queens', NULL, NULL, NULL),
    (138, 'LaGuardia Airport', 'Queens', NULL, NULL, NULL),
    (161, 'Midtown Center', 'Manhattan', NULL, NULL, NULL),
    (162, 'Midtown East', 'Manhattan', NULL, NULL, NULL),
    (163, 'Midtown North', 'Manhattan', NULL, NULL, NULL),
    (164, 'Midtown South', 'Manhattan', NULL, NULL, NULL),
    (230, 'Times Sq/Theatre District', 'Manhattan', NULL, NULL, NULL),
    (237, 'Upper East Side South', 'Manhattan', NULL, NULL, NULL),
    (238, 'Upper East Side North', 'Manhattan', NULL, NULL, NULL),
    (239, 'Upper West Side South', 'Manhattan', NULL, NULL, NULL),
    (240, 'Upper West Side North', 'Manhattan', NULL, NULL, NULL),
    (249, 'West Village', 'Manhattan', NULL, NULL, NULL),
    (250, 'Williamsburg (North Side)', 'Brooklyn', NULL, NULL, NULL),
    (251, 'Williamsburg (South Side)', 'Brooklyn', NULL, NULL, NULL),
    (255, 'Financial District North', 'Manhattan', NULL, NULL, NULL),
    (256, 'Financial District South', 'Manhattan', NULL, NULL, NULL);

